name: 'Terraform Deploy'
 
on:
  push:
    branches:
    - master
 

jobs:
  deploy:
    name: 'Terraform Deploy'
    environment: development
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout Code
      uses: actions/checkout@v2
 
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.5

    - name: Terraform Format
      run: terraform fmt -check -recursive
      working-directory: ./terraform

    - name: Login to Azure
      uses: azure/login@v1.5.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Terraform Init
      run: terraform init -backend-config="provider.tf"
      working-directory: ./terraform/development

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./terraform/development

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./terraform/development

    - name: Terraform Show
      run: terraform show
      working-directory: ./terraform/development