name: 'Terraform Destroy'
 
on:
    workflow_dispatch:
        inputs:
            confirmation:
                description: "Are you sure you want to run Terraform Destroy???"
                required: true
                type: choice
                options:
                    - yes
                    - no
                default: "no"
 

jobs:
  destroy:
    name: 'Terraform Destroy'
    environment: development
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout Code
      uses: actions/checkout@v2
 
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.5

    - name: Login to Azure
      uses: azure/login@v1.5.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    - name: Terraform Init
      run: terraform init -backend-config="provider.tf"
      working-directory: ./terraform/environment/development

    - name: Show Destroy plan
      run: terraform plan -destroy -state="provider.tf"
      continue-on-error: true
      working-directory: ./terraform/environment/development

    - name: Destroy resources jobs
      id: destroy
      run: terraform destroy -auto-approve -state="provider.tf"
      working-directory: ./terraform/environment/development